# Generated by Django 2.0.7 on 2020-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ashish',
            name='discription',
            field=models.TextField(default='ashish'),
        ),
        migrations.AddField(
            model_name='ashish',
            name='title',
            field=models.TextField(default='ashish'),
        ),
    ]
